version: "3.8"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
      - REDIS_HOST=redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`hris.localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app.entrypoints=web"
    depends_on:
      - postgres
      - redis
    command: ["start"]

  worker:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
      - REDIS_HOST=redis:6379
    depends_on:
      - postgres
      - redis
    command: ["worker"]

  seed:
    build: .
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
    command: ["seed"]
    restart: "no"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  asynqmon:
    image: hibiken/asynqmon
    platform: linux/amd64
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8081:8080"
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asynqmon.rule=Host(`asynqmon.localhost`)"
      - "traefik.http.services.asynqmon.loadbalancer.server.port=8080"
      - "traefik.http.routers.asynqmon.entrypoints=web"
