version: "3.8"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
      - REDIS_HOST=redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`hris.localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app.entrypoints=web"
    depends_on:
      - postgres
      - redis
    command: ["start"]

  worker:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
      - REDIS_HOST=redis:6379
    depends_on:
      - postgres
      - redis
    command: ["start-worker"]

  scheduler:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
      - REDIS_HOST=redis:6379
    depends_on:
      - postgres
      - redis
    command: ["start-scheduler"]

  seed:
    build: .
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_PORT=5432
    command: ["seed"]
    restart: "no"

  redis:
    image: redis
    ports:
      - "6380:6379"

  # comment out asynqmon cannot run in arm
  # asynqmon:
  #   image: hibiken/asynqmon
  #   platform: linux/amd64
  #   environment:
  #     - REDIS_ADDR=redis:6379
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - redis
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.asynqmon.rule=Host(`asynqmon.localhost`)"
  #     - "traefik.http.services.asynqmon.loadbalancer.server.port=8080"
  #     - "traefik.http.routers.asynqmon.entrypoints=web"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686" # UI (http://localhost:16686)
      - "4317:4317" # OTLP/gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_PORT=4317

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
